version: "3" #docker-composeファイルのバージョン
services:
  db: #サービス名、わかりやすければなんでもいい
    image: mysql:5.7 #使用するdocker imageの指定
    environment: #コンテナ起動時に渡す環境変数($docker-compose run -e )
      MYSQL_ROOT_PASSWORD: password #SQLのrootユーザーのパスワード(必須)
      MYSQL_DATABASE: root #コンテナ起動時に作成するデータベース名
    ports: 
        - "3306:3306" #<Host Port>:<Container Port>
    volumes:
        - ./tmp/db:/var/lib/mysql #永続的なデータの保存場所(volume)の指定、<Host Volume>:<Container Volume>

  web:
    build: . # buildするDockerfileの場所を指定
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0' "
    #PIDファイルの削除とrails serverの起動、localhost、port:3000で公開
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db #serviceの依存関係、コンテナの起動順や終了順を指定できる